### ISSUE TITLE
Consider semantic versioning

### ISSUE THREAD

**Issue by leetal** [spf13/pflag#104]
So, the time has come to start to introduce semantic versioning since this is the only "standard" that the GO community have been pushing for. Many of the package managers out there are using semantic versioning to determine if a newer release is available. Due to this, please consider adding a tagged release to this repo (and all other you have that don't have tagged versions). This would REALLY help us that relies on package managers du to project size A LOT! :)

**Comment by bogem** [comment]
Fixed
