### ISSUE TITLE
Question about optional params

### ISSUE THREAD

**Issue by percona-csalguero** [spf13/pflag#126]
Hi, 
I need to implement an optional param in my programs and I am wondering if there is a way to do it using this library.
The use case is to mimic MySQL behavior for `-p`
`-p` can be used as `-p<password here>` or just `-p` and in that case, the param is marked as set but empty and MySQL client will ask for a password. This way, you can avoid using a password in the command line.

Regards

**Comment by bogem** [comment]
Hello!
To check if flag is really changed, you can do this trick:
```go
func flagChanged(name string, fs *pflag.FlagSet) bool {
	flag := fs.Lookup(name)
	if flag == nil {
		return false
	}
	return flag.Changed
}
```

The whole example of your case:
```go
package main

import (
	"fmt"
	"os"

	"github.com/spf13/pflag"
)

func main() {
	fs := pflag.NewFlagSet("mysql", ContinueOnError)

	var password string
	fs.StringVarP(&password, "password", "p", "", "password for MySQL")
	fs.Parse()

	if password == "" && flagChanged("password", fs) {
		fmt.Println("Please set your password")
		os.Exit(1)
	}
}

func flagChanged(name string, fs *pflag.FlagSet) bool {
	flag := fs.Lookup(name)
	if flag == nil {
		return false
	}
	return flag.Changed
}

```

**Comment by percona-csalguero** [comment]
If you run that code, it produce: 
```
go run main.go -p
flag needs an argument: 'p' in -p
Usage of mysql:
  -p, --password string   password for MySQL
```

**Comment by bogem** [comment]
Yes, it fails if value for the flag isn't set. But actually it does the the whole work for you. If user sets -p flag without the password, pflag will logically ask user to enter the password.
So as I understand it solves the issue for you

**Comment by bogem** [comment]
In this case you don't need to use flagChanged function. Just compare the 'password' with blank string

**Comment by percona-csalguero** [comment]
1) pflag does not "ask" for a password
2) It doesn't solve the problem. calling the program without `-p` will also leave password="". What I need is an optional parameter. 
I am already working in the  feature and I'll PR later.
Thanks

**Comment by bogem** [comment]
So if password is "", you can just call the error in your program to ask user enter the password.

**Comment by percona-csalguero** [comment]
Just for clarification, a real world example.
If you start MySQL client you can do this:
`mysql -u user -ppassword` but that is a security issue because in your history there will be a password so, to avoid that, you can start MySQL client as `mysql -u user -p` and the client will prompt for a password:
```
$ mysql -u root -p
Enter password:
```
But, if you don't use `-p`:
```
mysql -u root
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

That's what I need to reproduce so I need an `optional` parameter that is, if a param is marked as optional, it won't produce the `flag needs an argument: 'p' in -p` message.

**Comment by percona-csalguero** [comment]
MySQL allows empty passwords so, checking if password == "" doesn't work for me.

**Comment by percona-csalguero** [comment]
Would you consider a PR implementing this feature?

**Comment by bogem** [comment]
Do you mean [BoolVarP](https://godoc.org/github.com/spf13/pflag#FlagSet.BoolVarP) flags?
```go
package main

import (
	"fmt"
	"os"

	"github.com/spf13/pflag"
)

func main() {
	fs := pflag.NewFlagSet("mysql", ContinueOnError)

	var password bool
	fs.BoolVarP(&password, "password", "p", "", "password for MySQL (required)")
	fs.Parse()

	if !password {
		fmt.Println("Please set password through `-p` flag")
		fs.Usage()
		os.Exit(1)
	}
}
```

**Comment by percona-csalguero** [comment]
No.
I know this is controversial but what I need is a string parameter that can
be empty.
I need these cases:
1) command -ppassword -> will set password in the variable associated with
-p
2) command -p -> will leave empty the variable associated with -p but
flag.Changed will be true
3) command (without -p) -> will leave empty the variable associated with -p
and flag.Changed will be false

Does it makes sense?
​

**Comment by bogem** [comment]
You can use [NoOptDefVal](https://godoc.org/github.com/spf13/pflag#Flag).
Flag will be actually changed, but you don't need flagChanged function.
```go
package main

import (
	"fmt"
	"os"

	"github.com/spf13/pflag"
)

func main() {
	fs := pflag.NewFlagSet("mysql", pflag.ContinueOnError)

	var password string
	fs.StringVarP(&password, "password", "p", "", "password for MySQL")
	fs.Lookup("password").NoOptDefVal = "without value" // use any string
	fs.Parse(os.Args)

	if password == ""  {
		fmt.Println("Please set your password")
		os.Exit(1)
	}
	if password == "without value") {
		// pronpt about password
	}
}

```

**Comment by bogem** [comment]
And please consider: `-p password` will not work, but `-p=password` and `-ppassword`.

**Comment by percona-csalguero** [comment]
That's why I cannot use NoOpDefault

**Comment by bogem** [comment]
Actually it's not possible to solve it. Just consider it user will call three bool flags in the row like this: `-abc`. How it should be parsed? 
And if the value after this flags will be an argument, this value will be used for flags, not as argument.

**Comment by bogem** [comment]
E.g. I call `app -abc arg`. `-abc` are boolean/nooptdefval flags and I want to use `arg` as argument for the app. `arg` will be used as value for `c`, not as argument.

**Comment by percona-csalguero** [comment]
Just closed this PR.

**Comment by bogem** [comment]
Can I close the issue?

**Comment by percona-csalguero** [comment]
yes please

**Comment by bogem** [comment]
The only solution here is to mention, what "you should not write value separately from the flag (like this: `-p password`). It will not work."
