### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by fd0** [spf13/pflag#131]
For [restic](https://github.com/restic/restic), we'll switch to `dep` shortly, and it would be very helpful if you could tag a release. Thanks!

https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by bogem** [comment]
Fixed

**Comment by fd0** [comment]
Thanks! I'm sorry to bother you again, but may I ask you to consider using semantic versioning? The tag you've used (`v1.0`) is not compatible as far as I can see. The equivalent would be `v1.0.0`. Would that be possible?

**Comment by bogem** [comment]
@fd0 Thank you for your note. I didn't even know that it's incompatible with semver...
Fixed!

**Comment by fd0** [comment]
Awesome, thanks!
