### ISSUE TITLE
Setting `NoOptDefVal` forces using `=` syntax

### ISSUE THREAD

**Issue by loderunner** [spf13/pflag#134]
Pflags accepts the following syntaxes for an integer argument:

```
--verbose=0
--verbose 0
-v 0
-v=0
```

Using this program:

```go
v := pflag.IntP("verbose", "v", 1, "make output verbose")
pflag.Parse()
fmt.Printf("verbosity: %d\n", *v)
```

I get the following results:

```
$ ./test
verbosity: 1
$ ./test --verbose=0
verbosity: 0
$ ./test --verbose 2
verbosity: 2
$ ./test -v 0
verbosity: 0
$ ./test -v=2
verbosity: 2
```

If I set `NoOptDefVal`, I get inconsistent behavior.

```go
v := pflag.IntP("verbose", "v", 1, "make output verbose")
verboseFlag := pflag.Lookup("verbose")
// In case of --verbose or -v with no arg, set to 2
verboseFlag.NoOptDefVal = "2"
pflag.Parse()

fmt.Printf("verbosity: %d\n", *v)
```

Here are the results:

```
$ ./test
verbosity: 1
$ ./test --verbose=0
verbosity: 0
$ ./test --verbose 2
verbosity: 2
$ ./test --verbose 3
verbosity: 2
$ ./test -v=0
verbosity: 0
$ ./test -v=1
verbosity: 1
$ ./test -v=2
verbosity: 2
$ ./test -v 1
verbosity: 2
```

I expected `-v 3` and `-v=3` to work the same way.

Is this a bug, or am I missing the point of `NoOptDefVal` ?

**Comment by loderunner** [comment]
I created a Pull request #135 

Here's the output I get (and expected).

```
$ ./test
verbosity: 1
$ ./test --verbose=0
verbosity: 0
$ ./test --verbose 3
verbosity: 3
$ ./test --verbose
verbosity: 2
$ ./test -v=0
verbosity: 0
$ ./test -v
verbosity: 2
$ ./test -v 1
verbosity: 1
```

**Comment by bogem** [comment]
It's not possible to solve this issue unequivocally. Just consider if user will call three bool flags in the row like this: `-abc`. How it should be parsed? That's why your [tests are failed](https://travis-ci.org/spf13/pflag/jobs/263063363#L268).
And actually it will considerably change the behaviour, that we do not want.

**Comment by alexkavon** [comment]
I do not fully understand the issue.

> It's not possible to solve this issue unequivocally. Just consider if user will call three bool flags in the row like this: -abc

If 3 bool flags are passed, shouldn't pflag know that -a is a bool. if -abc is shorthand for a string flag, then that would override -abc as a multiple bool flags possibility.

Am I missing something?

**Comment by eparis** [comment]
Imagine `a` is a string flag shorthand with `NoOptDefVal="a_default"`
Imagine there are bool shorthand flags `b` and `c`

What does -abc mean?  Does it mean:
`a = "bc"` and `b=false` `c=false`
or does it mean:
`a=a_default` and `b=true` `c=true`

**Comment by alexkavon** [comment]
Ah I understand what is meant by the above now.

> What does -abc mean? Does it mean:
> a = "bc" and b=false c=false
or does it mean:
a=a_default and b=true c=true
