### ISSUE TITLE
Backwards incompatibility with flag package

### ISSUE THREAD

**Issue by b1v1r** [spf13/pflag#147]
Single dash long options are not supported in pflag which yields a backwards incompatibility with the flag package and thus is not a true drop-in replacement. This also affects those moving from multiconfig, etc. It would be good to be able to optionally support single dash long options (e.g., `-option` vs only `--option`) for those that need a drop in replacement with extended features.

See PR https://github.com/spf13/pflag/pull/146

**Comment by seanschade** [comment]
It wouldn't be POSIX compliant though which is the point of this library.
