### ISSUE TITLE
Don't use "slice" word for --help of slice flags

### ISSUE THREAD

**Issue by ahmetb** [spf13/pflag#148]
(I'm using pflag via cobra and) if I have a StringSlice flag, I get this in --help:

      -r, --role stringSlice   Description of this flag bla bla bla

`stringSlice` flag is coming from **pflag**. It doesn't make sense to anyone who's not using Go, which just happens to be the programming language the command line tool is written in.

I think this should read:

      -r, --role strings...   Description of this flag bla bla bla

or 

      -r, --role=string [-r,--role=string[, ...]   Description of this flag bla bla bla

or some sort of better notation indicating the flag can be used for multiple times. Right now it's too cryptic (and forcing me to add explanation to the description of the flag).

**Comment by broady** [comment]
`strings...` also doesn't show how to use it (i.e., comma-delimited).

`-r,--role=string[, ...]` is nice.

Or something like `-r,--role=string[,string2,...]`

**Comment by ahmetb** [comment]
@broady truth is the flag isn't meant for comma-separated values as far as I know. Multiple values are provided by specifying the flag multiple times. Therefore calling the type `list`, and finding a notation indicating this probably would be better.

**Comment by ahmetb** [comment]
@eparis Interesting.

1. The [godoc for `StringSlice`](https://godoc.org/github.com/spf13/pflag#StringSlice) doesn't make it clear that it supports both multiple uses and comma-separated values.
2. I think the `--help` message still shouldn't use the word `slice`.
3. And in both ...Array and ...Slice cases, usage message in `--help` can be more descriptive to illustrate whether it is csv, or not, or both.

**Comment by stevenroose** [comment]
I think https://github.com/spf13/pflag/pull/150 solved this.

**Comment by ahmetb** [comment]
yep looks like #132 addressed stringSlice to strings as well. The input format isn't quite obvious though. I'll defer to maintainers whether to close this or not.

**Comment by cornfeedhobo** [comment]
@ahmetb Probably safe to close this issue now :)
