### ISSUE TITLE
arguments after boolean flag cannot be retrieved via Args()

### ISSUE THREAD

**Issue by mkishere** [spf13/pflag#154]
When putting a boolean flag at last just before arguments, it seems that pflag sees the argument as value supplied to the boolean flag instead of separate argument.

```go
lMode := pflag.BoolP("", "l", false, "use a long listing format")
pflag.Parse(args)
argArray := pflag.Args()
```
When calling like
```
ls -l /
```
argArray does not contains "/"

**Comment by eparis** [comment]
I'm not seeing it....
```
$ cat main.go
package main

import (
	"fmt"
	"github.com/spf13/pflag"
)

func main() {
	lMode := pflag.BoolP("", "l", false, "use a long listing format")
	pflag.Parse()
	argArray := pflag.Args()
	fmt.Printf("%#v: %#v\n", *lMode, argArray)
}

$ go build && ./test -l /
true: []string{"/"}
```

Can you supply your actual code?

**Comment by mkishere** [comment]
Sorry my bad. Turn out I was using a string slice passing into flag.Parse() and the arguments passing into was being stick togather in the first element of the slice, hence the bug.
