### ISSUE TITLE
Difference between Slice and Array flags

### ISSUE THREAD

**Issue by mweibel** [spf13/pflag#157]
first of all thanks for this awesome flag library. I use it through cobra which is amazing as well 👍 

I have my issues reading the documentation about the difference between Slice and Array flags. Could you point that out to me? I'd be more than happy to provide a PR with doc changes once I'm understanding what the difference is 😄 

Thanks!

**Comment by eparis** [comment]
I'm going from memory, am I correct that we only have the strangeness for 'string' slice/array. Everything else is just called a *Slice, right? The difference is that 1 of them, (StringSlice I believe) takes a CSV as arguments. so `--ss="v1,v2" --ss="v3"` will result in `[]string{"v1" , "v2", v3"}` where as the other (StringArray I believe) takes each argument exactly as written. so `--sa="v1,v2" --sa="v3" will result in `[]string{"v1,v2", "v3"}`.

I believe all of the 'non-string' flags types use a CSV parser, and there is little/no ambiguity.

**Comment by mweibel** [comment]
Thanks for the fast response. 
I just tested this and you're indeed correct about both things (tested with string slice/array and bool slice, array doesn't exist there). 
I'll make me a mental note to send a PR for clarifying this in the docs. 👍
