### ISSUE TITLE
sub-commands with global options + help?

### ISSUE THREAD

**Issue by prologic** [spf13/pflag#159]
Is this doable with pflag? Like what cobra supports but more minimal/library form.
(*cobra is way overkill for my use-case*)

**Comment by eparis** [comment]
pflag has `FlagSets` which you can manage as you see fit. But the concept of subcommands and global flags and all of that are a cobra concept. You're going to have to rebuild cobra :-(

**Comment by prologic** [comment]
I see; Thanks!
