### ISSUE TITLE
POSIX compliance

### ISSUE THREAD

**Issue by innovativeprogrammingorg** [spf13/pflag#185]
I have noticed that programs using this package require the use of 2 '-' delimiters for single character, when the standard is using just 1 '-' delimiter for these single character options. This makes it confusing for many users, decreasing usability. See POSIX.1-2017 command line argument conventions(single character flags) and the GNU extension of these conventions(multi-character flags) for more details

**Comment by moorereason** [comment]
If what you say is true, they're using this package incorrectly.  pflag supports what you're describing and is intended to be used that way.

**Comment by eparis** [comment]
see for example https://godoc.org/github.com/spf13/pflag#IntP

you must have a long version (which require `--`) but you can also have a short version, which requires `-`

**Comment by innovativeprogrammingorg** [comment]
Ok, you are right, thank you for your time. I will notify the forementioned projects
