### ISSUE TITLE
expose Writer via `Output`

### ISSUE THREAD

**Issue by wkhere** [spf13/pflag#230]
Hi!

A small feature request:

Can the FlagSet's Writer be exposed via `Output` method, as it is done in original Go's flag package.

Example use case:

You have special usage function which is printing both 'defaults' (as returned via FlagUsages) and your custom message. You want to print custom message to the same writer as PrintDefaults does it, and you don't know which one is it.
Not artificial example - a popular practice is that the writer is either stderr when user typed wrong flags, or stdout for `-h`; but, the logic to decide it doesn't belong to the usage function where you'd want to use it, right

**Comment by mckern** [comment]
Related: #220 and #241

**Comment by wkhere** [comment]
Yep, merging any of these would do it

**Comment by wkhere** [comment]
Solved by #220, thx guys
