### ISSUE TITLE
A way to add custom header to CommandLine.Usage

### ISSUE THREAD

**Issue by Felixoid** [spf13/pflag#232]
Hello, thank you for a great project!

I'd like to add the custom header to the output of pflag.Usage. I don't really see a way to do it in the current implementation since the header is https://github.com/spf13/pflag/blob/master/flag.go#L921-L922.

It's quite easy with a footer by changing a `pflag.ErrHelp = errors.New("test")`, and I wonder if there any way to change the header?

**Comment by mckern** [comment]
I did this by [defining a new FlagSet](https://github.com/mckern/spiry/blob/master/cmd/spiry/main.go#L35) and [overriding `Usage()`](https://github.com/mckern/spiry/blob/master/cmd/spiry/main.go#L116-L123) in one of my projects; maybe this will help?

**Comment by Felixoid** [comment]
I've tried it, but don't remember, why it didn't work.

The workaround, which I've implemented, is tweaking the footer instead with `pflag.ErrHelp`

https://github.com/innogames/graphite-ch-optimizer/blob/master/graphite-ch-optimizer.go#L178

Thank you for a suggestion, @mckern
