### ISSUE TITLE
Override usage message

### ISSUE THREAD

**Issue by kargakis** [spf13/pflag#28]
Would it make sense to override the usage message of a flag like overriding [default](https://godoc.org/github.com/spf13/pflag#Set) values? Is there any way currently to do it?

**Comment by kargakis** [comment]
This issue stems from the fact that people may add their default values in the flag message and if that command is wrapped and the defaults need to change, there is no way to get rid of that hardcoded default. 

Another solution other than overriding the message would be to show the defaults next to the message, probably parenthesized (I think this already happens in the standard flag library) so there will be no need to hardcode the defaults in the first place.

**Comment by eparis** [comment]
I'm not sure I understand...  All (Flag fields)[https://github.com/spf13/pflag/blob/master/flag.go#L148] are public. So aren't you able to update them?

**Comment by kargakis** [comment]
/facepalm

Went through all this and didn't even check the *basic* struct:)

Thanks, closing this....
