### ISSUE TITLE
Do we actually need this package?

### ISSUE THREAD

**Issue by qlcom** [spf13/pflag#280]
flag package in standard library can parse flag with `--flag` syntax.

**Comment by cornfeedhobo** [comment]
lol. then ... don't use it, no?

**Comment by eparis** [comment]
The main difference is that posix flags have always considered `-` and `--` to be different. The standard library flag package does not see those as different. If you would like your program to handle flags similarly to most other unix/linux program ever, then spf13/pflag is a good option. If you (and especially your users) are willing to accept the potential ambiguity and inconsistency of the standard library then there is not a compelling reason to use this package. Aside from maybe a couple of extra flag types you can find here.
