### ISSUE TITLE
Question: Copyright?

### ISSUE THREAD

**Issue by Zaba505** [spf13/pflag#283]
@spf13 I think this library is fantastic! I have worked on porting it to Rust ([pflag](https://github.com/z5labs/pflag)) and I'm just wondering if I need to copy over the license? I'm not sure if licenses cover ports to another language.

**Comment by alessio** [comment]
> I'm not sure if licenses cover ports to another language.

They don't. Licenses cover the source code that was released under their terms.

**Comment by Zaba505** [comment]
@alessio Thanks!
