### ISSUE TITLE
How can I exclude the space separator from StringSliceP?

### ISSUE THREAD

**Issue by thevan4** [spf13/pflag#284]
How can I exclude the space separator from StringSliceP?

From:
```go
go run main.go -a one,data with spaces,two
```
get a slice like:
```go
[]string{"one","data with spaces","two"}

**Comment by kpym** [comment]
Have you tried `go run main.go -a "one,data with spaces,two"`  or `go run main.go -a one,"data with spaces",two` ? These are the standard ways to use parameters with spaces.

**Comment by thevan4** [comment]
> 
> 
> Have you tried `go run main.go -a "one,data with spaces,two"` or `go run main.go -a one,"data with spaces",two` ? These are the standard ways to use parameters with spaces.

I apologize for the delay in responding.
I was able to identify that the problem is not with pflag, apparently my bug fell on the strange behavior of Cobra with pflag. When working with the Cobra I get the duplicate sections and neglecting quotation marks when setting parameters.
In any case, if someone needs an answer with an example of pflag:
```go
package main

import (
	"fmt"
	"os"

	"github.com/spf13/pflag"
	"github.com/spf13/viper"
)

var defaultSlice = []string{}
var sliceName = "slice"

func main() {
	viperConfig := viper.New()

	pflag.StringSliceP(sliceName, "s", defaultSlice, "slice")

	pflag.Parse()
	if err := viperConfig.BindPFlags(pflag.CommandLine); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	fmt.Println(viperConfig.GetStringSlice(sliceName), "len:", len(viperConfig.GetStringSlice(sliceName)))
}
```
```bash
go run main.go run -s "test1,spaces test,test2"
```
