### ISSUE TITLE
Question : best way to translate `failf` messages ?

### ISSUE THREAD

**Issue by kpym** [spf13/pflag#290]
If I want to write a non english interface, what is the best way to translate the error messages ?

**Comment by cornfeedhobo** [comment]
@kpym There is currently no easy way. There was some work on this in #114. I think if you really wanted to, you could maybe hijack stdout and do the translation there, but that seems like a mess.

I've been giving this a little thought recently on [my fork](https://github.com/cornfeedhobo/pflag/issues/14) and was looking at using the new i18n package, but didn't come up with an elegant API yet. If you'd like to try your hand at a PR on my fork, I'd definitely take a look!

**Comment by kpym** [comment]
@cornfeedhobo Thanks for your advice. Probably I'll use `text/transform` to hijack this.
