### ISSUE TITLE
Bug: `Bool` after `StringArray` gets parsed into array.

### ISSUE THREAD

**Issue by gabyx** [spf13/pflag#303]
Not sure if that is a bug:

With cobra do:

```go
var patterns []string

cmd := &cobra.Command{Use: "cli [flags]", Short: "do something"}
cmd.Flags().StringArrayVar(&patterns, "patterns", nil,
		"Specified glob patterns matching paths.")
cmd.Flags().BoolVar(&all, "all", false,`All flag...`)
```

Invocation `cli --patterns --all`. Results in `patterns[0] == "--all"`.

**Comment by cornfeedhobo** [comment]
This is user error. String* will blindly accept any argument following the flag, then continue parsing other flags.

I can see an argument for adjusting the parser to search for flags and present the user an error message, but this would need to be configurable to allow developers the same control they have now.

**Comment by gabyx** [comment]
Ahh, the problem was that I was expecting (because the doc is strange)  `--patterns` to take multiple values

```
--patterns a b c d --otherflag
```
which is not implemented so, but
```
--patterns a --patterns b --patterns c --patterns d --otherflag
```
works

**Comment by cornfeedhobo** [comment]
@gabyx Ah, yeah, you kind of have to look at the tests to fully get it, and they aren't exactly structured clearly. Something I'd like to fix in my fork eventually. FWIW, you can also pass a csv, e.g.:

```plain
--patterns a,b,c,d --otherflag
```

Cheers!
