### ISSUE TITLE
Add support for repeated "counter" flags

### ISSUE THREAD

**Issue by Luzifer** [spf13/pflag#31]
As a developer I want to give my users the option to set the log level of my application without knowing about internal numberings of log levels. A common practice is a repeated `-v` flag to increase the log level.

Example:

```go
pflag.CounterFlagP(&loglevel, "verbose", "v", 0, "Increase log level")

# ./myapp
loglevel == 0

# ./myapp -v
loglevel == 1

# ./myapp -vvvv
loglevel == 4
```

Default value used as a `+n` for the count of used flag or left out?

**Comment by eparis** [comment]
closed. fixed. /me prays it works.
