### ISSUE TITLE
use single - for full name flag

### ISSUE THREAD

**Issue by adnan-kamili** [spf13/pflag#310]
We had earlier designed our CLI interface using single hyphens only, e.g.

mycli -config ./config.yaml

Now, we want to standardize it as per pflag convention for single and double hyphens. But to prevent a new version of our application from breaking some scripts which may have been written using old syntax we want to add a hidden flag for old single hyphen flags. So I want the following three to be equivalent:

mycli -config ./config.yaml
mycli --config ./config.yaml
mycli -c ./config.yaml

And will mark the first as hidden (or deprecated).

Is it possible?

**Comment by cornfeedhobo** [comment]
@adnan-kamili I don't think this would be possible, because the support for concatenated shorthands, e.g. `-abc` == `--a --b --c`.

**Comment by adnan-kamili** [comment]
Thanks for confirming. Is it possible to override the default error message:

unknown shorthand flag: 'k' in -k

And it gets displayed twice.

**Comment by rfjakob** [comment]
@adnan-kamili I'm in the same situation as you, switching from `flag` to `pflag` without breaking existing users.

Preprocessing os.Args like this does the trick for me:

```
// convertToDoubleDash converts args like "-debug" (Go stdlib `flag` style)
// into "--debug" (spf13/pflag style).
// gocryptfs v2.1 switched from `flag` to `pflag`, but we obviously want to stay
// cli-compatible, and this is the hack to do it.
func convertToDoubleDash(osArgs []string) (out []string) {
	out = append(out, osArgs...)
	for i, v := range out {
		// Leave "-h" alone so the help text keeps working
		if v == "-h" {
			continue
		}
		// Don't touch anything after "--"
		if v == "--" {
			break
		}
		// Convert "-foo" to "--foo"
		if len(v) >= 2 && v[0] == '-' && v[1] != '-' {
			out[i] = "-" + out[i]
		}
	}
	return out
}
```

**Comment by adnan-kamili** [comment]
Thanks for sharing your trick.
