### ISSUE TITLE
argument parsing with mixed named and positional arguments is broken

### ISSUE THREAD

**Issue by steveeJ** [spf13/pflag#32]
We're using pflag in rkt and are having unexpected results with the command line parsing.
See https://github.com/coreos/rkt/issues/1235 for the specific example.

**Comment by eparis** [comment]
I commented over there, but I think this is working as intended.  bool type flags do not accept whitespace even with --long-form versions of the flag.

**Comment by eparis** [comment]
After discussion in the PR I do not think it is broken. It follows the conventions used in coreutils like `ls`. Which one may not believe that anything that old is the pinnacle of UI design, but if people have handled this long I think we can continue to do so.
