### ISSUE TITLE
pflag is not a main package

### ISSUE THREAD

**Issue by aldochaconc** [spf13/pflag#354]
Hello everyone,
I'm facing an issue when I use
`go install github.com/spf13/pflag@latest`
I'm having this error:
```
go install -v [github.com/spf13/pflag@latest](http://github.com/spf13/pflag@latest)
go: downloading [github.com/spf13/pflag](http://github.com/spf13/pflag) v1.0.5
package [github.com/spf13/pflag](http://github.com/spf13/pflag) is not a main package
```
What I'm doing wrong here? I'm missing an specification right?
Sorry for asking such a newbie question, but I'm not a GO user, I'm actually trying to figure out why my pipeline is broken.

Thanks to all in advance!

**Comment by p7r0x7** [comment]
Please try `GO111MODULE=off go get github.com/spf13/pflag`, the default behavior for this command changed with go1.18.
