### ISSUE TITLE
StringSlice flag and default values

### ISSUE THREAD

**Issue by miekg** [spf13/pflag#40]
So running this code with the latest master, seem to *add* any value you give on the commandline to the default set as defined in the flag. Is this the intended behavior? (This is also new behavior - didn't git bisect)
```
package main

import (
	"fmt"

	"github.com/spf13/pflag"
)

func main() {
	fFlag := pflag.StringSlice("a", []string{"1", "3"}, "a bogus option")
	pflag.Parse()
	fmt.Printf("%v\n", fFlag)
}
```

Running:
```
% go run flagtest.go --a 2
&[1 3 2]
```

**Comment by eparis** [comment]
ok. I'll try to look at it today. I think I know how to fix it.  I added the ability to do

`-a 2 -a 3 -a 4 -a 5` and you will get `[]string{2,3,4,5}`

But I wasn't getting rid of the default on the first `-a`

**Comment by eparis** [comment]
see #41 where I believe this is fixed.

**Comment by eparis** [comment]
I'm going to mark this as closed, since your test case works (as well as the new go tests I wrote).  Let me know if it doesn't do what you want/need!

**Comment by miekg** [comment]
Looks legit. Thanks for the quick turnaround.
