### ISSUE TITLE
Tap tap...is this thing on?

### ISSUE THREAD

**Issue by larsks** [spf13/pflag#416]
I was banging my head against the fact that my build was failing with...

```
./main.go:80:31: flag.CommandLine.Output undefined (type *pflag.FlagSet has no field or method Output)
```

...even though it's clearly been there for years, when I realized that there hasn't been a new release cut since 2019. Any chance we could tag a new release, or should I look elsewhere for a sane command line parsing library? That would make me sad, but I know what it's like trying to find time to maintain things.

**Comment by tomasaschan** [comment]
There's been some development in #385 around maintenance status for this library. I'm hoping we can, among other things, tag a new release soon.
