### ISSUE TITLE
Help for subcommands are not working as expected.

### ISSUE THREAD

**Issue by MohamedAshiqrh** [spf13/pflag#70]
I had a sample cli with go flags implemented, now I just replaced "flag" with "flag "github.com/spf13/pflag""

``
 $command subcommand --help 
``

This command still displays the main command's help.
The same works fine with the go flags.

**Comment by spf13** [comment]
This wouldn't be an issue with pflag as it has no knowledge of sub commands, which live in a layer above the flags.

If you are using spf13/cobra for your commander then the behavior you seek is already supported. 

In Cobra
`command sub --help`
`command help sub` 
are handled identically

If there is indeed an issue with Cobra or if I'm misunderstanding the issue please (re)open with more information.

**Comment by MohamedAshiqrh** [comment]
Thanks for update, I am using cobra now.

**Comment by pablochacin** [comment]
This is still an issue with `pflag`. As `pflag` presents itself as a drop-in replacement for go's `flag` package, then this issue should be resolved in `pflag` (instead of suggesting using `cobra`) or at least be listed as an incompatibility with `flag`
