### ISSUE TITLE
Calling Set on StringSlice flag appends result rather than setting it

### ISSUE THREAD

**Issue by daniellowtw** [spf13/pflag#71]
I have a question regarding calling `Set` on a string slice flag.

Running the following code against master produces the following result

```go
package main

import (
  "fmt"
  "github.com/spf13/pflag"
)

func main() {
  f := pflag.StringSlice("test", []string{"a"}, "")
  fmt.Printf("1: %v\n", f) // Expected: "[a]" Actual :"[a]"
  pflag.Set("test", "b")
  fmt.Printf("2: %v\n", f) // Expected: "[b]" Actual :"[b]"
  pflag.Set("test", "c")
  fmt.Printf("3: %v\n", f) // Expected: "[c]" Actual :"[b,c]"
}
```

```shell
$ go run main.go 
1: &[a]
2: &[b]
3: &[b c]
```

I expect that when I call `Set` on the flag `test` I overwrite whatever value it was before. However, the second call to `Set` actually appends to the existing slice. Is this behaviour intended?

**Comment by eparis** [comment]
Yes, we had people who wanted to be able to do
`./binary --test=bob --test=sue --test=sally`
and get []string{bob, sue, sally}

**Comment by daniellowtw** [comment]
OK. Thanks for the quick response!
I'll just use string and do a split to get the behaviour I wanted.

**Comment by eparis** [comment]
We/you could do a new string/slice type in pflag, I'd merge it. Should be 99% cp'd and minor changes in https://github.com/spf13/pflag/blob/master/string_slice.go#L24

**Comment by daniellowtw** [comment]
The reason for the current behaviour makes sense, as long as it is clear to the developer that `Set` is akin to setting the flag in the command line (resulting in the appending behaviour) rather than setting the variable in code.

https://github.com/spf13/pflag/blob/master/flag.go#L361
```go
// Set sets the value of the named flag.
func (f *FlagSet) Set(name, value string) error {
```

This misled me which was the reason for this issue.

I might look into your proposed change later if I have the time.
