### ISSUE TITLE
StringSliceVar is appending to string in first index of slice, rather than appending to the slice

### ISSUE THREAD

**Issue by treeder** [spf13/pflag#79]
Eg:

for instance `env vars:  [a=b x=y]` rather than the expected `[a=b, x=y]`

```go
var envVars []string
...
myCmd.PersistentFlags().StringSliceVarP(&envVars, "env", "e", []string{}, "Environment variables.")
```

**Comment by eparis** [comment]
you've have to show your exact command line...
--env="a=b x=y" should do what you said...

**Comment by treeder** [comment]
Oh, sorry. Command line is:

`-e x=y -e a=b`

**Comment by treeder** [comment]
And I'd expect that to end up as multiple entries in the slice, rather than one entry with the strings concatenated. Or maybe I'm missing the point of StringSliceVar?

**Comment by treeder** [comment]
Sorry, my bad, it is working properly.
