### ISSUE TITLE
Grouping flags?

### ISSUE THREAD

**Issue by fd0** [spf13/pflag#95]
Hi,

is it possible to group flags so that they appear together in the `--help` text? I'm using `pflag` in my [backup program](https://github.com/restic/restic), there I have for example the options to expire backups according to a policy. Before (with the `go-flags`) library the options were nicely grouped together (in the order they were defined):

```
$ restic forget --help
Usage:
  restic [OPTIONS] forget [snapshot ID] ...
[...]
[forget command options]
      -l, --keep-last=    keep the last n snapshots
      -H, --keep-hourly=  keep the last n hourly snapshots
      -d, --keep-daily=   keep the last n daily snapshots
      -w, --keep-weekly=  keep the last n weekly snapshots
      -m, --keep-monthly= keep the last n monthly snapshots
      -y, --keep-yearly=  keep the last n yearly snapshots
          --keep-tag=     alwaps keep snapshots with this tag (can be specified multiple times)
          --hostname=     only forget snapshots for the given hostname
          --tag=          only forget snapshots with the tag (can be specified multiple times)
      -n, --dry-run       do not delete anything, just print what would be done
```

Now with `pflag` and `cobra` they are printed in alphabetical order:

```
[...]
Usage:
  restic forget [flags] [snapshot ID] [...]

Flags:
  -n, --dry-run                do not delete anything, just print what would be done
      --hostname string        only forget snapshots for the given hostname
  -d, --keep-daily int         keep the last n daily snapshots
  -H, --keep-hourly int        keep the last n hourly snapshots
  -l, --keep-last int          keep the last n snapshots
  -m, --keep-monthly int       keep the last n monthly snapshots
      --keep-tag stringSlice   always keep snapshots with this tag (can be specified multiple times)
  -w, --keep-weekly int        keep the last n weekly snapshots
  -y, --keep-yearly int        keep the last n yearly snapshots
      --tag stringSlice        only forget snapshots with the tag (can be specified multiple times)
[...]
```

Is there a way to group some flags so that they are printed together?

**Comment by bogem** [comment]
If #113 will be merged, you will be able to order flags how you want.

**Comment by fd0** [comment]
That'd be awesome! Unfortunately it looks like this library is dead :cry:

**Comment by bogem** [comment]
Fixed in #113

**Comment by fd0** [comment]
@bogem @eparis Thank you very much!

**Comment by fd0** [comment]
Hm. I don't have any idea on how to use it with cobra. The sample program at https://gist.github.com/1b3ccbf904682e0b9fd113ee42a47471 always prints the flags in alphabetical order:
```
go run main.go -h    
Usage:
   [flags]

Flags:
  -a, --alpha string     help for alpha (default "empty")
  -e, --epsilon string   help for epsilon (default "empty")
  -z, --zulu string      help for zulu (default "empty")
err: <nil>
```

**Comment by bogem** [comment]
Hm, very interesting. I am trying to figure out not what's wrong.

**Comment by fd0** [comment]
Hm, it seems that cobra creates new flag sets all over the place...

**Comment by fd0** [comment]
There's also a bug: When you call `cmdRoot.LocalFlags()` before defining any flags, the help message is empty but the flags are still valid: https://gist.github.com/9cc52f7c0f5fc9d2cb84a1fcb43b11dc

```
$ go run main.go -h
Usage:
   [flags]
err: <nil>

$ go run main.go -a foobar
do something
err: <nil>
```

**Comment by bogem** [comment]
I think, we should create PR to make SortFlags work correct in cobra

**Comment by bogem** [comment]
> There's also a bug: When you call cmdRoot.LocalFlags() before defining any flags, the help message is empty but the flags are still valid
Yes, it's cobra's issue. You can make issue in cobra, so I will try to figure out and fix it.

**Comment by bogem** [comment]
`cmd.Flags().SortFlags() = false` doesn't work for cobra. I think, we should add one more property to `cobra.Command` to switch the sort of flags.

**Comment by fd0** [comment]
I'll create two issues in cobra, so we can continue the discussion there

**Comment by fd0** [comment]
https://github.com/spf13/cobra/issues/403
https://github.com/spf13/cobra/issues/404
