### ISSUE TITLE
Customizing help text for slices?

### ISSUE THREAD

**Issue by fd0** [spf13/pflag#96]
Hi,

the text that is printed after e.g. a string slice option is not helpful for end-users who do not know Go. For example, defining a flag like this:
```Go
var tags []string

func init() {
    f.StringSliceVar(&tags, "tag", []string{}, "only forget snapshots with the tag (can be specified multiple times)")
}
```

is printed in the help text in the following way:
```
  -y, --keep-yearly int        keep the last n yearly snapshots
      --tag stringSlice        only forget snapshots with the tag (can be specified multiple times)
```

That's not really helpful. Is there a way to define the text that is printed after the flag?

**Comment by moorereason** [comment]
The only way to set the place holder text is to use back-quotes in the description. See https://godoc.org/github.com/spf13/pflag#UnquoteUsage

**Comment by fd0** [comment]
Ah, that's subtle, but solves my problem! For anybody stumbling upon this issue, adding the flag in this way:
```go
f.StringSliceVar(&tags, "tag", []string{}, "only forget snapshots with the `tag` (can be specified multiple times)")
```
yields the following help text:
```
--keep-tag tag       always keep snapshots with this tag (can be specified multiple times)
```
